#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail
umask 077

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# wrangler_secret NAME VALUE — push a secret to the deployed Worker.
wrangler_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | npx wrangler secret put "$name" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Worker secret $name (run: npx wrangler secret put $name)")
    warn "failed to set Worker secret $name"
  fi
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} Worker secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "draftlink setup — deps, D1, GitHub OAuth app, secrets, deploy"

# ── Stage 1: bootstrap project deps + D1 + base URL ──────────────────────
stage "Bootstrap"
say "Install dependencies…"
[[ -d node_modules ]] || npm install --no-fund --no-audit
say ""
step "Find your workers.dev subdomain: dash.cloudflare.com → Workers & Pages (right sidebar)."
note "Or reuse an existing pattern like someproject.<subdomain>.workers.dev"
default_base=$(_existing BASE_URL || true)
[[ -z "$default_base" ]] && default_base="https://draftlink.REPLACE_WITH_YOUR_SUB.workers.dev"
prompt_text="Base URL for this deployment e.g. draftlink.yoursub.workers.dev:"
[[ "$default_base" != *REPLACE* ]] && prompt_text="Base URL for this deployment [Enter = ${default_base}]:"
while :; do
  BASE_URL=""
  ask BASE_URL "$prompt_text"
  [[ -z "$BASE_URL" ]] && BASE_URL="$default_base"
  [[ "$BASE_URL" != *"://"* ]] && BASE_URL="https://${BASE_URL}"
  BASE_URL="${BASE_URL%/}"
  if [[ "$BASE_URL" =~ ^https://[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+\.[A-Za-z]{2,}$ && "$BASE_URL" != *REPLACE* ]]; then
    break
  fi
  warn "That doesn't look like a host, e.g. draftlink.yoursub.workers.dev — try again (Ctrl-C aborts)."
done
write_env BASE_URL "$BASE_URL"
say ""
say "Ensuring a D1 database named 'draftlink' exists on this account…"
raw=$(npx wrangler d1 list --json 2>/dev/null || true)
DB_ID=$(printf '%s' "$raw" | python3 -c 'import sys, json
try:
    dbs = json.load(sys.stdin)
    print(next((d.get("uuid", "") for d in dbs if d.get("name") == "draftlink"), ""))
except Exception:
    print("")')
if [[ -z "$DB_ID" ]]; then
  say "Not found — creating…"
  out=$(npx wrangler d1 create draftlink 2>&1 || true)
  DB_ID=$(printf '%s' "$out" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)
fi
if [[ -n "$DB_ID" ]]; then
  printf '  %s✓ using%s D1 draftlink (%s)\n' "$GREEN" "$RESET" "$DB_ID"
  python3 - "$DB_ID" <<'EOF'
import re, sys
path = "wrangler.jsonc"
src = open(path).read()
open(path, "w").write(re.sub(r'"database_id":\s*"[^"]*"', f'"database_id": "{sys.argv[1]}"', src))
EOF
else
  SKIPPED+=("wire D1 database id into wrangler.jsonc (npx wrangler d1 create draftlink, paste uuid)")
  warn "couldn't resolve a D1 database id — patch wrangler.jsonc manually before deploying"
fi

# ── Stage 2: create the GitHub OAuth App, capture client id ───────────────
stage "GitHub OAuth App"
say "We need an OAuth App so draftlink can identify you via GitHub."
open_url "https://github.com/settings/developers"
step "Click 'New OAuth App'."
step "Application name:  anything, e.g. draftlink"
step "Homepage URL:      $BASE_URL"
step "Application description: optional — leave blank"
step "Redirect URIs → Redirect URI:  $BASE_URL/auth/callback"
note "   (if the field is blank, click 'Add redirect URI' first)"
step "Allow wildcard matching:   leave UNCHECKED (tokens must never match subdomains)"
step "Enable Device Flow:        leave UNCHECKED (draftlink uses the browser web flow)"
step "'Expire user access tokens': doesn't matter — draftlink never stores tokens. Skip it."
step "Click 'Register application'."
pause "Registered? Press Enter to copy the client ID."
step "Copy the Client ID shown on the app page."
ask GITHUB_CLIENT_ID "Paste the Client ID:"
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"

# ── Stage 3: generate the client secret ───────────────────────────────────
stage "Client secret"
say "You should already be on the app page you just created."
step "In the 'Client secrets' section, click 'Generate a new client secret' (may ask for your password/2FA)."
step "Copy the secret — GitHub shows it exactly once."
ask_secret GITHUB_CLIENT_SECRET "Paste the client secret:"
write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"

# ── Stage 4: session signing secret (auto-generated) ──────────────────────
stage "Session secret"
if existing=$(_existing SESSION_SECRET) && [[ -n "$existing" ]]; then
  say "SESSION_SECRET already in $ENV_FILE — keeping it."
  SESSION_SECRET="$existing"
else
  say "Generating a random 32-byte secret for signing session cookies…"
  SESSION_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi
write_env SESSION_SECRET "$SESSION_SECRET"

# ── Stage 5: deploy, then push secrets + migrate remote D1 ───────
stage "Deploy + secrets + database"
say "First deploy creates the Worker so secrets have somewhere to live."
if confirm "Run 'wrangler deploy' now?"; then
  npx wrangler deploy
else
  SKIPPED+=("deploy (run: npx wrangler deploy)")
fi
say ""
say "Pushing the three secrets to the Worker…"
wrangler_secret GITHUB_CLIENT_ID   "$GITHUB_CLIENT_ID"
wrangler_secret GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
wrangler_secret SESSION_SECRET     "$SESSION_SECRET"
say ""
say "Applying pending D1 migrations to the production database."
if confirm "Run 'wrangler d1 migrations apply draftlink --remote' now?"; then
  npm run db:remote
else
  SKIPPED+=("remote D1 migrations (run: npm run db:remote)")
fi

# ── Stage 5: verify live ──────────────────────────────────────────────────
stage "First sign-in"
say "Deployed. Time to log in for real."
open_url "$BASE_URL/login"
step "Click 'Sign in with GitHub' and authorize the draftlink app."
step "You should land on the dashboard (empty for now)."
pause "Signed in?"
say "Next steps once you're in:"
step "Open $BASE_URL/keys and create an API key for your agent/CLI."
if confirm "Install the draftlink CLI globally (npm install -g .)?"; then
  npm install -g --no-fund --no-audit .
  say "Done — run 'draftlink auth login' from anywhere and paste the key."
else
  say "Skip. Use ./bin/draftlink from this repo, or 'npm install -g .' later."
fi
step "Upload:     draftlink upload plan.html --title 'My plan' --project myrepo"
# ──────────────────────────────────────────────────────────────────────────

finish
